on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild LGTVCompanion.sln
        env:
          Configuration: ${{ matrix.configuration }}
      - uses: actions/upload-artifact@v3
        with:
          name: LGTVCompanion-${{ matrix.configuration }}
          path: x64/${{ matrix.configuration }}/
      - uses: actions/upload-artifact@v3
        with:
          name: LGTVCompanion-Setup-${{ matrix.configuration }}
          path: LGTV Companion Setup/bin/${{ matrix.configuration }}/
